// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Migrations;

[DbContext(typeof(AuthDbContext))]
[Migration("20251129135318_AddVerificationCodeTable")]
partial class AddVerificationCodeTable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Main.Auth.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Role")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Users");
            });

        modelBuilder.Entity("Main.Auth.Entities.VerificationCode", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreateDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("VerificationCodes");
            });

        modelBuilder.Entity("Main.Auth.Entities.VerificationCode", b =>
            {
                b.HasOne("Main.Auth.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
